// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vc8lluIFPRrVUEWPY6UrUwjyCa6v_Fo',
    appId: '1:535724110346:web:f2974d4c07df9f5ecc25f3',
    messagingSenderId: '535724110346',
    projectId: 'shopbystock',
    authDomain: 'shopbystock.firebaseapp.com',
    storageBucket: 'shopbystock.appspot.com',
    measurementId: 'G-RGXX4V4H6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsm1Ixb9Hz63z9glZeo60lbfHk25iaS70',
    appId: '1:535724110346:android:ccf59e96486ca087cc25f3',
    messagingSenderId: '535724110346',
    projectId: 'shopbystock',
    storageBucket: 'shopbystock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOg7pa431OS48FV6dxRc8N3T8KGtd2AzE',
    appId: '1:535724110346:ios:dab58b338d092cf5cc25f3',
    messagingSenderId: '535724110346',
    projectId: 'shopbystock',
    storageBucket: 'shopbystock.appspot.com',
    iosBundleId: 'com.ebenezer.shopby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOg7pa431OS48FV6dxRc8N3T8KGtd2AzE',
    appId: '1:535724110346:ios:aeaf946b760122ffcc25f3',
    messagingSenderId: '535724110346',
    projectId: 'shopbystock',
    storageBucket: 'shopbystock.appspot.com',
    iosBundleId: 'com.example.shopby.RunnerTests',
  );
}
